export const extensionView = `
  <div class="extension-heading-row"><div><div class="eyebrow" data-i18n="extensionEyebrow">EXTENSION STUDY · THINK LIKE A SCIENTIST</div><h2 id="extension-heading" data-i18n="extensionHeading">Same solution. Different cells?</h2><p data-i18n="extensionSubtitle">Look beyond the usual rule and test a hypothesis about individual red blood cells.</p></div><button id="extension-reset" class="text-button"><span aria-hidden="true">↺</span> <span data-i18n="restartActivity">Restart activity</span></button></div>
  <ol class="extension-steps" aria-label="Activity progress"><li data-step="1" aria-current="step"><button type="button" data-extension-step="1" aria-current="step"><span>01</span><span data-i18n="observeHypothesisStep">Observe and hypothesise</span></button></li><li data-step="2"><button type="button" data-extension-step="2"><span>02</span><span data-i18n="testStep">Test</span></button></li><li data-step="3"><button type="button" data-extension-step="3"><span>03</span><span data-i18n="explainStep">Explain</span></button></li></ol>
  <div id="extension-step-1" class="extension-panel">
    <div class="extension-observe-grid"><figure class="micrograph-card"><div class="micrograph biological-photo"><svg id="micrograph-image" viewBox="0 0 1150 620" role="img" aria-label="The supplied blood photograph with straight biological leader-line labels"><image href="./assets/Red%20Blood%20Cell.jpg" x="0" y="0" width="782" height="620" preserveAspectRatio="xMidYMid meet"/><g class="biological-leaders"><line x1="650" y1="306" x2="816" y2="306"/><line x1="333" y1="512" x2="816" y2="512"/></g><g class="biological-labels"><text x="831" y="300" data-i18n="shrunkenLabelLine1">B · Shrunken</text><text x="831" y="338" data-i18n="shrunkenLabelLine2">RBC</text><text x="831" y="506" data-i18n="regularLabelLine1">A · RBC with</text><text x="831" y="544" data-i18n="regularLabelLine2">regular shape</text></g></svg></div><figcaption><p class="photo-source">圖片來源：<a href="https://unsplash.com/@niaid" target="_blank" rel="noopener noreferrer">https://unsplash.com/@niaid</a></p><p class="illustration-caption" data-i18n="photoCaption">Original photo supplied by the teacher, with biological leader-line labels added as a separate layer. The saline conditions below are the activity’s assumptions, not verified from this photo.</p></figcaption></figure>
    <div class="extension-question-card"><span class="question-number" data-i18n="observationQuestion">THE OBSERVATION</span><h3 data-i18n="observationHeading">Most look regular. A few look wrinkled.</h3><p data-i18n="observationScenario">These red blood cells are immersed in 0.9% sodium chloride solution, with a water potential of −794 kPa.</p><div class="thought-box"><strong data-i18n="observationPrompt">Why does the solution affect individual cells differently? Predict the initial water potentials of cells A and B.</strong><div class="potential-comparisons"><div class="potential-comparison"><label for="compare-psi-a" data-i18n="initialComparisonA">Initial water potential: cell A</label><select id="compare-psi-a"><option value="">?</option><option value="higher">&gt;</option><option value="lower">&lt;</option><option value="equal">=</option></select><span data-i18n="salineSolutionWord">Sodium chloride solution</span></div><div class="potential-comparison"><label for="compare-psi-b" data-i18n="initialComparisonB">Initial water potential: cell B</label><select id="compare-psi-b"><option value="">?</option><option value="higher">&gt;</option><option value="lower">&lt;</option><option value="equal">=</option></select><span data-i18n="salineSolutionWord">Sodium chloride solution</span></div></div></div><p class="evidence-note" data-i18n="photoLimit">A picture alone cannot confirm a cell’s starting water potential. We need a controlled test.</p><button id="extension-next-1" class="primary-button"><span data-i18n="testHypothesis">Test the hypothesis</span><span aria-hidden="true">→</span></button></div></div>
  </div>
  <div id="extension-step-2" class="extension-panel" hidden>
    <div id="extension-hypothesis-required" class="extension-question-card"><p data-i18n="chooseHypothesesFirst">Choose the initial water-potential relationship for both cells in stage 01 before testing.</p><button id="extension-to-hypothesis" class="primary-button" data-i18n="returnToHypothesis">Return to observation and hypothesis</button></div>
    <div class="extension-test-card" id="extension-test-card"><div class="extension-test-header"><div><span class="question-number" data-i18n="sharedBathLabel">ONE SHARED SALINE SOLUTION</span><h3 id="extension-test-heading"></h3></div><div class="extension-test-actions"><button id="extension-pause" class="small-action"></button></div></div><div class="extension-saline-banner"><span data-i18n="sharedSaline">Same 0.9% saline solution</span><strong>Ψ = −794 kPa</strong><span class="extension-water-legend"><i class="water-dot"></i><span data-i18n="waterMolecule">Water molecule</span></span><span class="salt-legend"><i></i><span data-i18n="saltParticles">Dissolved salt (schematic)</span></span></div>
      <p class="evidence-note hypothesis-model-note" data-i18n="hypothesisModelNote">Example starting potentials follow your hypothesis: &gt; −700 kPa, = −794 kPa, &lt; −900 kPa. The saline stays at −794 kPa.</p><div class="extension-chambers"><div class="extension-chamber"><div class="extension-cell-header"><strong data-i18n="cellA">Cell A</strong><span id="extension-initial-a"></span></div><canvas id="extension-canvas-a" role="img"></canvas><div class="extension-metrics"><span id="extension-flow-a"></span><strong id="extension-volume-a"></strong></div></div><div class="extension-chamber"><div class="extension-cell-header"><strong id="extension-cell-other"></strong><span id="extension-initial-other"></span></div><canvas id="extension-canvas-other" role="img"></canvas><div class="extension-metrics"><span id="extension-flow-other"></span><strong id="extension-volume-other"></strong></div></div></div>
    </div>
    <div id="extension-test-result" class="extension-test-result" hidden aria-live="polite"><h3 id="extension-result-title"></h3><ul id="extension-result-points"></ul><div id="extension-photo-comparison" class="photo-comparison" aria-live="polite"></div><button id="extension-revise-hypothesis" class="text-button" data-i18n="reviseHypothesis">Revise your hypothesis and test again</button><button id="extension-to-explain" class="primary-button"><span data-i18n="explainObservation">Explain the observation</span><span aria-hidden="true">→</span></button></div>
  </div>
  <div id="extension-step-3" class="extension-panel" hidden>
    <div class="extension-question-card final-explanation"><span class="question-number" data-i18n="evidenceConclusion">FROM EVIDENCE TO AN EXPLANATION</span><h3 data-i18n="whatLearned">Do your test results match the microscope photo?</h3><p id="extension-review-note" class="evidence-note">Choose both hypotheses in stage 01 to load the final model results here.</p><div class="table-scroll"><table class="extension-summary"><thead><tr><th data-i18n="cell">Cell</th><th data-i18n="initialWaterPotential">Initial Ψ (kPa)</th><th data-i18n="solutionRelative">Solution relative to this cell</th><th data-i18n="netMovementShort">Net movement</th><th data-i18n="observation">Observation</th></tr></thead><tbody id="extension-summary-body"></tbody></table></div><div id="extension-summary-comparison" class="photo-comparison"></div><button id="extension-revise-summary" class="text-button" data-i18n="reviseHypothesis">Revise your hypothesis and test again</button><p class="evidence-note" data-i18n="explainPhotoCells">Use the comparisons to explain the cells in the microscope photo.</p><div class="extension-final-questions"><div><label for="infer-a" data-i18n="inferA">A cell confirmed to remain unchanged most likely began with…</label><select id="infer-a"><option value="" data-i18n="chooseAnswer">Please select</option><option value="higher" data-i18n="higherThanSaline">Higher water potential than saline</option><option value="equal" data-i18n="equalToSaline">Equal water potential to saline</option><option value="lower" data-i18n="lowerThanSaline">Lower water potential than saline</option></select></div><div><label for="infer-b" data-i18n="inferB">A cell that shrank by osmosis must have begun with…</label><select id="infer-b"><option value="" data-i18n="chooseAnswer">Please select</option><option value="higher" data-i18n="higherThanSaline">Higher water potential than saline</option><option value="equal" data-i18n="equalToSaline">Equal water potential to saline</option><option value="lower" data-i18n="lowerThanSaline">Lower water potential than saline</option></select></div></div><button id="extension-check" class="primary-button" data-i18n="checkExplanation">Check my explanation</button><div id="extension-final-feedback" class="extension-final-feedback" hidden aria-live="polite"></div><p class="evidence-note" data-i18n="inferenceLimit">Under our assumptions, the unchanged cell began near −794 kPa; a cell that shrank began above −794 kPa. The image cannot tell us its exact initial value, and real images can also be affected by preparation artefacts.</p><button id="extension-return" class="text-button" data-i18n="backToLab">← Back to the osmosis lab</button></div>
  </div>
`;
